services:
  c-jumpbox-01:
    container_name: c-jumpbox-01
    hostname: c-jumpbox-01.acme-infinity-servers.com
    profiles: ["all", "ch03", "ch04", "ch05", "ch07"]
    build: 
      context: machines/c-jumpbox-01
      dockerfile: Dockerfile
    networks:
      public:
        ipv4_address: 172.16.10.13
      corporate:
        ipv4_address: 10.1.0.13

  c-backup-01:
    container_name: c-backup-01
    hostname: c-backup-01.acme-infinity-servers.com
    profiles: ["all", "ch05", "ch07", "ch09"]
    build: 
      context: machines/c-backup-01
      dockerfile: Dockerfile
    networks:
      corporate:
        ipv4_address: 10.1.0.14

  c-redis-01:
    container_name: c-redis-01
    hostname: c-redis-01.acme-infinity-servers.com
    profiles: ["all", "ch07", "ch09"]
    build: 
      context: machines/c-redis-01
      dockerfile: Dockerfile
    networks:
      corporate:
        ipv4_address: 10.1.0.15
  p-ftp-01:
    container_name: p-ftp-01
    hostname: p-ftp-01.acme-infinity-servers.com
    profiles: ["all", "ch03"]
    build: 
      context: machines/p-ftp-01
      dockerfile: Dockerfile
    networks:
      public:
        ipv4_address: 172.16.10.12
      corporate:
        ipv4_address: 10.1.0.12
    ports:
        - "20-21:20-21"
        - "65500-65515:65500-65515"

networks:
  public:
    name: public
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_public
    ipam:
      config:
        - subnet: "172.16.10.0/24"

  corporate:
    internal: true
    name: corporate
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_corporate
    ipam:
      config:
        - subnet: "10.1.0.0/24"