services:
  c-jumpbox-01:
    container_name: c-jumpbox-01
    hostname: c-jumpbox-01.acme-infinity-servers.com
    build: 
      context: machines/c-jumpbox-01
      dockerfile: Dockerfile
    networks:
      public:
        ipv4_address: 172.16.10.13
      corporate:
        ipv4_address: 10.1.0.13
  c-backup-01:
    container_name: c-backup-01
    hostname: c-backup-01.acme-infinity-servers.com
    build: 
      context: machines/c-backup-01
      dockerfile: Dockerfile
    networks:
      corporate:
        ipv4_address: 10.1.0.14
  c-redis-01:
    container_name: c-redis-01
    hostname: c-redis-01.acme-infinity-servers.com
    build: 
      context: machines/c-redis-01
      dockerfile: Dockerfile
    networks:
      corporate:
        ipv4_address: 10.1.0.15
  p-ftp-01:
    container_name: p-ftp-01
    hostname: p-ftp-01.acme-infinity-servers.com
    build: 
      context: machines/
      dockerfile: p-ftp-01/Dockerfile
    networks:
      public:
        ipv4_address: 172.16.10.12
      corporate:
        ipv4_address: 10.1.0.12
    volumes:
      - appdata:/mnt/scripts
  p-web-01:
    container_name: p-web-01
    hostname: p-web-01.acme-infinity-servers.com
    build: 
      context: machines/p-web-01
      dockerfile: Dockerfile
    networks:
      public:
        ipv4_address: 172.16.10.10
    volumes:
      - appdata:/mnt/scripts/
  p-web-02:
    container_name: p-web-02
    hostname: p-web-02.acme-infinity-servers.com
    image: wordpress:latest
    volumes:
      - wpdata:/var/www/html
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_HOST=c-web-02-db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    
    networks:
      public:
        ipv4_address: 172.16.10.11
      corporate:
        ipv4_address: 10.1.0.11
  c-web-02-db:
    container_name: c-web-02-db
    hostname: c-web-02-db.acme-infinity-servers.com
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      corporate:
        ipv4_address: 10.1.0.17


volumes:
  appdata:
  dbdata:
  wpdata: 

networks:
  public:
    name: public
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_public
    ipam:
      config:
        - subnet: "172.16.10.0/24"

  corporate:
    internal: true
    name: corporate
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_corporate
    ipam:
      config:
        - subnet: "10.1.0.0/24"