name: Integration Testing
on:
  workflow_dispatch:
  schedule:
  - cron:  '0 0 * * *'

jobs:
  install_with_run_sh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploys Lab with run.sh
        id: deploy
        run: |
          sudo ./run.sh deploy
        working-directory: ./lab
      
      - name: Test Lab
        id: test
        run: | 
          sudo ./run.sh status
        working-directory: ./lab
      
      - name: Slack Notification Failure
        id: notify_failure
        
        if: steps.init.outcome != 'success' || steps.test.outcome != 'success'
        run: |
          ${{ github.run_id }}"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"[FAILURE] Integration test (https://github.com/dolevf/Black-Hat-Bash/actions/runs/${{github.run_id}})"}' ${{secrets.SLACK_WEBHOOK}}

      - name: Slack Notification Success
        id: notify_success
        
        if: steps.init.outcome == 'success' && steps.test.outcome == 'success'
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"[SUCCESS] Integration test (https://github.com/dolevf/Black-Hat-Bash/actions/runs/${{github.run_id}})"}' ${{ secrets.SLACK_WEBHOOK }}
          head -100 log.txt
      